### ISSUE TITLE
Parameter of empty list results in TypeError

### ISSUE THREAD

**Issue by friedger** [leather-io/extension#1111]
When calling `register` function of https://explorer.stacks.co/txid/0x89cff4241836c31c6a47bc268225b379f076a04709a27ec4665b7747d191d9c2?chain=mainnet
on https://stacks-pool-registry.pages.dev/pools the call results in an half-empty screen and the console log shows:

`Uncaught (in promise) TypeError: c is undefined`

Screenshot:
![Screenshot from 2021-04-12 22-17-49](https://user-images.githubusercontent.com/1449049/114456260-ef031880-9bdc-11eb-924f-7350fef488a7.png)

**Comment by aulneau** [comment]
@markmhx can we confirm this is still an issue?

**Comment by markmhendrickson** [comment]
@friedger are you still seeing this? You're the only one to report this so far iirc.

**Comment by friedger** [comment]
Seems fixed.

**Comment by friedger** [comment]
This is still a problem with empty integer lists, as seen in Boom dev

@dantrevino

**Comment by friedger** [comment]
Stacks wallet version 2.24.1

console output:
```
TypeError: u is undefined
    f clarityValue.js:111
    f clarityValue.js:133
    h function-argument-item.tsx:21
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    fe index.js:509
    xe index.js:418
    xe index.js:418
    xe index.js:408
    We index.js:303
    write index.js:633
    X index.js:281
    We index.js:301
    C wallet.hooks.ts:123
react-dom.production.min.js:216:199
```

**Comment by friedger** [comment]
Looks like the current transaction js version is does not include the fix https://github.com/blockstack/stacks.js/blob/master/CHANGELOG.md#201-beta1-2021-07-26

**Comment by dantrevino** [comment]
Yes, confirmed I'm seeing this as well.  Same wallet version specified by @friedger above.

**Comment by beguene** [comment]
This is fixed in our dev branch, can you try this build ?
https://github.com/hirosystems/stacks-wallet-web/releases/tag/v2.24.0-beta.11

**Comment by fbwoolf** [comment]
@beguene do you know why this version number is behind main? We released `v2.24.1` yesterday ...do I need to do something after the revert PR?

**Comment by beguene** [comment]
Yes I was surprised too. As such it should auto-increment correctly after merge into main, but the beta version is still wrong. If you don't find out or don't have time, I will have a look at the github actions tomorrow.

**Comment by Eshwari007** [comment]
@friedger The test passed and issue is no longer be able to be reproduced in https://stacks-pool-registry.pages.dev/pools with the release: https://github.com/hirosystems/stacks-wallet-web/releases/tag/v2.24.0-beta.11
I tested it on a pool registry as well.

cc @beguene @andresgalante
