### ISSUE TITLE
[connect] How can we set permissions so that a gaia bucket is created for publish_data rights?

### ISSUE THREAD

**Issue by jorishermans** [leather-io/extension#346]
With connect, I get an error "Error: "userSession" is read-only" ...

When I want to retrieve data now I get 'Error: Missing readURL' and we guess it has something todo with the permissions ... also the application is not in the list of the profile.json of that person.

This is the url that fails ... https://app.guidle.me/p/friedger.id/fd284ba2-6a78-9a8c-67c8-e008bc5bec68

**Comment by hstove** [comment]
@jorishermans , when did this user sign in? We recently fixed a bug where the profile.json was not updated (11 days ago). If friedger logged in before then, then it's possible his profile.json would not get the URL. Is that what you're seeing?

**Comment by jorishermans** [comment]
@hstove I will ask him at the chat to look into it and give an answer here and directly here in github @friedger

**Comment by friedger** [comment]
> With connect, I get an error "Error: "userSession" is read-only" ...

This is a usage error. The userSession must not change in the auth flow.

**Comment by friedger** [comment]
@hstove I tried logging out and in again just now. The issue is not related to the recent bug fix.

**Comment by friedger** [comment]
I see a similar issue on speed-spend.netlify.app. Publishing data works for some users for others it don't.

**Comment by hstove** [comment]
I believe this was fixed by #379 , which is deployed. @friedger or @jorishermans could you confirm? Thanks!

**Comment by friedger** [comment]
I still have the same issue. I thought #578 would solve the issue (or is it not yet deployed?)

**Comment by hstove** [comment]
@friedger in the extension or the hosted authenticator? I need to check back on when we last published the extension. It's definitely deployed on the hosted version.

**Comment by hstove** [comment]
Was this related to the profile.json filename location issue? @friedger

**Comment by friedger** [comment]
The url in question is now working. This issue can be closed.
