### ISSUE TITLE
When attempting to generate an error message for transaction signing I get an infinite spinner

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#361]
When attempt to make a contract call on a contract that doesn’t exist to generate an error message for transaction signing but I am getting an infinite spinner instead of an error message.

![Screen Shot 2020-05-01 at 10.29.51 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/55078b78-b90e-43f6-a368-9ad0db0df227)

![Screen Shot 2020-05-01 at 10.29.40 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/6cc06bf6-f6d4-4a07-96a9-4c96a6dfd7c5)

**Comment by hstove** [comment]
This should be fixed in the `feat/clarity` PR now

**Comment by timstackblock** [comment]
Still getting the infinite spinner but I think its because sidecar is down. The faucet and new explorer are struggling as well so I am guessing this is a wide spread problem.

This makes me wonder should an error message be returned if this happens? Currently the infinite spinner keeps going until it gets a response. A good example of this is how the connect app serves an error message if it is rate limited or cannot create a username.

What are your thoughts?

**Comment by hstove** [comment]
Let's add a timeout to this and show that error message as well, good catch Tim!

**Comment by markmhendrickson** [comment]
@hstove Mind creating a ticket for that timeout and error message feature and link here?

**Comment by hstove** [comment]
Ticket created in #390 - can we QA this again?

**Comment by timstackblock** [comment]
This is resolved
