### ISSUE TITLE
Mozilla firefox issue when trying to use connect to login to the explorer app

### ISSUE THREAD

**Issue by timstackblock** [leather-io/extension#776]
Mozilla firefox issue when trying to use connect to login to explorer, I can login to explorer with chrome without an issue but cannot login with firefox

Video of issue http://somup.com/crVIVHol7x

If I am logged in already I get this screen but the links are not clickable and I am stuck on the page

<img width="1039" alt="Screen Shot 2021-01-12 at 8 50 31 PM" src="https://user-images.githubusercontent.com/49165468/104396024-e9336380-5517-11eb-9607-4759643a8eb5.png">

If I login with my seed phrase I get this screen with an infinite spinner

<img width="1158" alt="Screen Shot 2021-01-12 at 8 50 08 PM" src="https://user-images.githubusercontent.com/49165468/104396100-0bc57c80-5518-11eb-832c-092e7b16a13a.png">

**Comment by hstove** [comment]
@timstackblock I see this is already in QA, but I pushed a fix for auth issues on FF last night. I also just tested with the latest and it worked.

**Comment by timstackblock** [comment]
This is still happening for me I keep getting the same issue where we pop new tabs and the same logged out page appears on the new tab and the user is not logged in with out extension.

video of the issue: http://somup.com/crVYYmoul6

**Comment by timstackblock** [comment]
`Uncaught (in promise) Error: Your transaction was broadcasted, but we lost communication with the app you started with.`

Video of the issue is here: http://somup.com/crnV3Hos7J

The message above is the new error in the console when trying to login to an app using the extension on FF. I either get an infinite spinner or the login link isnt clickable.

<img width="1403" alt="Screen Shot 2021-02-01 at 5 40 24 PM" src="https://user-images.githubusercontent.com/49165468/106527858-efcd4f00-64b5-11eb-919f-2d9d7dba1ad0.png">

**Comment by hstove** [comment]
This is because the explorer needs to update to the latest version of Connect (the canary version).

I've opened #359 with that update

**Comment by philiphacks** [comment]
@hstove I'm getting the same/similar issue (see gif below). This is on Brave browser. Is this something on my side? I used the test app from https://github.com/blockstack/ux/tree/release/canary/packages/test-app

Also, can I run this through local mocknet? Doesn't seem to work either. I don't understand how Gaia fits in here.
![recording](https://user-images.githubusercontent.com/577420/109472266-32ad2300-7a72-11eb-9b65-94a9f82ca980.gif)

**Comment by philiphacks** [comment]
@hstove never mind, I cleared the repo and cloned + checked out canary branch again, and it works now.
